### ISSUE TITLE
Enable service worker

### ISSUE THREAD

**Issue by chetanraj** [chetanraj/snpt#26]

**Comment by kimuradev** [comment]
I'll help with this :)

**Comment by kimuradev** [comment]
PR #27 was opened. As suggestion would be great to transform this web app in a PWA. You could use some PWA functions such as offline navigation, cache storage, etc. Would be great!

**Comment by chetanraj** [comment]
> PR #27 was opened. As suggestion would be great to transform this web app in a PWA. You could use some PWA functionalities such as offline navigation, cache storage, etc. Would be great!

sure that would be greate @kimuradev, would you be able to help !!

**Comment by kimuradev** [comment]
for sure :)

**Comment by chetanraj** [comment]
@kimuradev - the current SW is having issue, skipWaiting is happening, not loading the new content

**Comment by kimuradev** [comment]
@chetanraj actually it´s not an issue. It´s the expected behaviour from SW. The content will be updated when you close your browser and open again. To make it automatically, you should configure your SW to enable the skipWaiting function. To do that I'll suggest you to open another issue to see if someone can help with this.
